#!/usr/bin/python3
"""Finds the factors of a number and prints"""
import sys


def factorise():
    try:
        with open(sys.argv[1], "r") as files:

            line = []
            for line in files:
                if not line:
                    return
                num = int(line)
                for i in range(2, num + 1):
                    if num % i == 0:
                        print("{:d}={:d}*{:d}".format(num, int(num / i), i))
                        break
    except FileNotFoundError:
        print("Error! File not found")
    finally:
        return


if __name__ == "__main__":
    factorise()
