#!/usr/bin/python3
"""n = p × q. The problem is to find these two primes, given only n."""
import sys

def is_prime(num):
	if num == 2:
		return True
	for i in range (2, num):
		if num % i == 0:
			return False
	return True
def rsa_factor():
	line = []
	with open(sys.argv[1], "r") as file:
		for line in file:
			num = int(line)
			for q in range(2, num + 1):
				p = int(num / q)
				print("--in for loop q = {}".format(q))
				if is_prime(q) and is_prime(p) and num % q == 0:
					print("{}={}*{}".format(num, p, q))
					return
	print("End of rsa_factor")
	return

if __name__ == "__main__":
	rsa_factor()
